language: node_js
node_js:
  - "10"
branches:
  only:
    - master
addons:
  chrome: stable
before_install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
install:
  - cd ./functions && npm install && cd ..
  - npm install
cache:
  directories:
    - node_modules
script:
  - ng lint
  - npm run test-headless
  - ng build --prod
deploy:
  provider: firebase
  skip_cleanup: true
  script: firebase use default && firebase deploy --token "$FIREBASE_TOKEN"
