language: node_js
node_js:
  - "10"

branches:
  only:
    - master

addons:
  chrome: stable

before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli

cache:
  npm: true
  directories:
    - node_modules

script:
  - ng-lint
  - ng build --prod

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
