language: node_js
node_js:
  - "10"
branches:
  only:
    - master
addons:
  chrome: stable
before_install:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
install:
  - cd ./functions && npm install && cd ..
  - npm install
cache:
  directories:
    - node_modules
jobs:
  include:
    - stage: test
      script: ng lint
    - script: npm run test-headless
    - stage: compile
    - script: ng build --prod
    - stage: deploy
    - script: firebase deploy --token "$FIREBASE_TOKEN" --project=i-memer
stages:
  - test
  - compile
  - name: deploy
    if: branch = master
